In [69]:
import pandas as pd
import sqlite3

In [73]:
df = pd.read_excel("Cleaned_Dataset.xlsx")

In [75]:
conn = sqlite3.connect("orders.db")

In [77]:
df.to_sql("Orders", conn, if_exists="replace", index=False)

1200

In [81]:
pd.read_sql_query("""
SELECT *
FROM Orders;
""", conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20 00:00:00,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04 00:00:00,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,No Coupon,Facebook,1325.06
1197,ORD201197,2023-07-13 00:00:00,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22 00:00:00,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11 00:00:00,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

Selected Columns

In [83]:
pd.read_sql_query("""
SELECT OrderID, Product, TotalPrice
FROM Orders;
""", conn)

        OrderID  Product  TotalPrice
0     ORD200000  Monitor     2853.10
1     ORD200001    Phone      302.70
2     ORD200002   Tablet     2753.40
3     ORD200003    Chair      273.19
4     ORD200004  Printer     2504.04
...         ...      ...         ...
1195  ORD201195     Desk      107.04
1196  ORD201196  Monitor     1325.06
1197  ORD201197   Tablet      873.68
1198  ORD201198    Chair     1050.08
1199  ORD201199   Tablet     2242.32

[1200 rows x 3 columns]

WHERE

In [85]:
pd.read_sql_query("""
SELECT *
FROM Orders
WHERE PaymentMethod='Online';
""", conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
1,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
2,ORD200011,2024-02-17 00:00:00,C93861,Monitor,3,49.14,831 Main St,Online,Returned,TRK48234646,7,SAVE10,Email,147.42
3,ORD200022,2023-01-29 00:00:00,C34416,Monitor,2,49.62,633 Main St,Online,Pending,TRK75937350,2,SAVE10,Google,99.24
4,ORD200024,2024-10-30 00:00:00,C17470,Laptop,2,230.95,956 Main St,Online,Delivered,TRK28775057,3,WINTER15,Referral,461.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,ORD201173,2024-10-04 00:00:00,C82921,Monitor,1,208.36,703 Main St,Online,Shipped,TRK31079911,4,FREESHIP,Email,208.36
254,ORD201181,2023-07-27 00:00:00,C70246,Desk,3,158.74,293 Main St,Online,Pending,TRK45708320,7,FREESHIP,Instagram,476.22
255,ORD201192,2024-02-28 00:00:00,C72007,Chair,3,432.85,999 Main St,Online,Pending,TRK16240916,4,No Coupon,Instagram,1298.55
256,ORD201196,2024-03-04 00:00:00,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,No Coupon,Facebook,1325.06
257,ORD201197,2023-07-13 00:00:00,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68

ORDER BY

In [87]:
pd.read_sql_query("""
SELECT *
FROM Orders
ORDER BY TotalPrice DESC;
""", conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200789,2023-08-17 00:00:00,C57276,Tablet,5,691.28,183 Main St,Online,Delivered,TRK75899752,10,SAVE10,Email,3456.40
1,ORD201122,2023-06-07 00:00:00,C38840,Monitor,5,678.19,766 Main St,Online,Returned,TRK32496970,8,No Coupon,Facebook,3390.95
2,ORD200632,2023-05-02 00:00:00,C67260,Laptop,5,678.16,463 Main St,Gift Card,Delivered,TRK38229104,7,WINTER15,Facebook,3390.80
3,ORD200469,2023-11-26 00:00:00,C13877,Chair,5,676.98,893 Main St,Cash,Cancelled,TRK17254691,5,No Coupon,Facebook,3384.90
4,ORD200328,2023-02-28 00:00:00,C18404,Tablet,5,674.04,546 Main St,Online,Cancelled,TRK89401624,7,SAVE10,Google,3370.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD200336,2023-12-29 00:00:00,C88174,Laptop,1,18.20,441 Main St,Debit Card,Pending,TRK10143345,4,SAVE10,Instagram,18.20
1196,ORD200542,2023-11-14 00:00:00,C49726,Tablet,1,17.98,934 Main St,Cash,Cancelled,TRK20739460,6,FREESHIP,Email,17.98
1197,ORD200240,2023-07-12 00:00:00,C14983,Tablet,1,17.24,255 Main St,Online,Pending,TRK93444157,2,FREESHIP,Instagram,17.24
1198,ORD200863,2024-05-20 00:00:00,C98276,Phone,1,14.06,471 Main St,Credit Card,Pending,TRK74207282,5,SAVE10,Referral,14.06
1199,ORD201161,2023-10-16 00:00:00,C32570,Phone,1,11.39,826 Main St,Cash,Cancelled,TRK35969968,6,WINTER15,Email,11.39

COUNT

In [92]:
pd.read_sql_query("""
SELECT COUNT(*) AS TotalOrders
FROM Orders;
""", conn)

   TotalOrders
0         1200

AVG

In [95]:
pd.read_sql_query("""
SELECT AVG(TotalPrice) AS AverageOrderValue
FROM Orders;
""", conn)

   AverageOrderValue
0          1053.9683

SUM

In [98]:
pd.read_sql_query("""
SELECT SUM(TotalPrice) AS TotalRevenue
FROM Orders;
""", conn)

   TotalRevenue
0    1264761.96

GROUP BY

In [101]:
pd.read_sql_query("""
SELECT Product,
COUNT(*) AS Orders
FROM Orders
GROUP BY Product;
""", conn)

   Product  Orders
0    Chair     178
1     Desk     170
2   Laptop     173
3  Monitor     163
4    Phone     156
5  Printer     181
6   Tablet     179

GROUP BY + SUM

In [103]:
pd.read_sql_query("""
SELECT Product,
SUM(TotalPrice) AS Sales
FROM Orders
GROUP BY Product
ORDER BY Sales DESC;
""", conn)

   Product      Sales
0    Chair  195620.11
1  Printer  195612.61
2   Laptop  192126.56
3   Tablet  186568.95
4  Monitor  175651.41
5     Desk  167459.93
6    Phone  151722.39

GROUP BY + AVG

In [106]:
pd.read_sql_query("""
SELECT PaymentMethod,
AVG(TotalPrice) AS AvgOrder
FROM Orders
GROUP BY PaymentMethod;
""", conn)

  PaymentMethod     AvgOrder
0          Cash  1056.041829
1   Credit Card  1127.553974
2    Debit Card  1001.556810
3     Gift Card  1070.973565
4        Online  1017.220698

In [111]:
conn.close()